# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: pretty-format-json
        args: [ '--no-sort-keys','--autofix' ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4  # Use the latest stable version
    hooks:
      - id: ruff
        name: ruff-lint
        args: [ --fix ]
      - id: ruff-format
        name: ruff-format